# App: Client Profile Module
# Package: ui
# File: Makefile
# Version: 0.0.8
# Author: Bobwares
# Date: 2025-06-08T09:02:15Z
# Description: Task shortcuts for building, starting, and testing the Next.js UI.

.PHONY: build start test

build:
	npm run build

start:
	npm run start

test:
	npm test --silent
