# App: Client Profile Module
# Package: ui
# File: Makefile
# Version: 0.0.15
# Author: Bobwares
# Date: 2025-06-09T02:59:45Z
# Description: Task shortcuts for building, starting, testing, and installing the Next.js UI.

.PHONY: install build start test

install:
	npm install --legacy-peer-deps

build:
	npm run build

start:
	npm run start

test: install
	npm test --silent
